services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper2me_bot
    volumes:
      - whisper2me_bot_data:/whisper2me_bot_data
    env_file:
      - bot_config.env
    deploy:
      restart_policy:
        condition: any
        window: 120s
    
volumes:
  whisper2me_bot_data: